#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# --- ADD THESE LINES ---
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm use default --silent
# -----------------------

pnpm exec lint-staged